### ISSUE TITLE
creation of migration file fails

### ISSUE THREAD

**Issue by jmartsch** [Luis85/FlowtiCore#2]
When I output the path before line 111 of FlowtiMigration.php with `bd($path.$name.'.php');` the path is something like `'D:\htdocs\myproject\website\dist\site\modules\FlowtiCore\src/../migrations/1624967310.php'`
as you can see there are traversal dots in the path, which should not be there.
So the file can not be created.

I am on window btw

**Comment by jmartsch** [comment]
Fix for this problem would be to modify the createMigrationFile method in FlowtiMigrationService.php like so:
`return $dto->saveAsFile(wire()->config->urls->siteModules ."{$this->className}migrations/');`

I changed it, but now the next error occurs: `syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)`

**Comment by Luis85** [comment]
Thanks for your report :)
The problem with this solution
`return $dto->saveAsFile(wire()->config->paths->siteModules.'FlowtiCore/migrations/');`
is, you cant put your Module in a subfolder like /site/modules/Process/ProcessModuleXYZ

I added self::MIGRATION_PATH to the constructor of the Service, which makes it somehow more thigtly coupled but I guess its ok for now. 

Will be fixed with the next push.
